/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ru.kashtanov.dad.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Dad service. Represents a row in the &quot;Dad_Dad&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ru.kashtanov.dad.model.impl.DadModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ru.kashtanov.dad.model.impl.DadImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Dad
 * @generated
 */
@ProviderType
public interface DadModel extends BaseModel<Dad>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dad model instance should use the {@link Dad} interface instead.
	 */

	/**
	 * Returns the primary key of this dad.
	 *
	 * @return the primary key of this dad
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dad.
	 *
	 * @param primaryKey the primary key of this dad
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dad ID of this dad.
	 *
	 * @return the dad ID of this dad
	 */
	public long getDadId();

	/**
	 * Sets the dad ID of this dad.
	 *
	 * @param dadId the dad ID of this dad
	 */
	public void setDadId(long dadId);

	/**
	 * Returns the group ID of this dad.
	 *
	 * @return the group ID of this dad
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this dad.
	 *
	 * @param groupId the group ID of this dad
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dad.
	 *
	 * @return the company ID of this dad
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dad.
	 *
	 * @param companyId the company ID of this dad
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dad.
	 *
	 * @return the user ID of this dad
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dad.
	 *
	 * @param userId the user ID of this dad
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dad.
	 *
	 * @return the user uuid of this dad
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dad.
	 *
	 * @param userUuid the user uuid of this dad
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dad.
	 *
	 * @return the user name of this dad
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dad.
	 *
	 * @param userName the user name of this dad
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dad.
	 *
	 * @return the create date of this dad
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dad.
	 *
	 * @param createDate the create date of this dad
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dad.
	 *
	 * @return the modified date of this dad
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dad.
	 *
	 * @param modifiedDate the modified date of this dad
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this dad.
	 *
	 * @return the name of this dad
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dad.
	 *
	 * @param name the name of this dad
	 */
	public void setName(String name);

	/**
	 * Returns the weight of this dad.
	 *
	 * @return the weight of this dad
	 */
	public double getWeight();

	/**
	 * Sets the weight of this dad.
	 *
	 * @param weight the weight of this dad
	 */
	public void setWeight(double weight);

	/**
	 * Returns the description of this dad.
	 *
	 * @return the description of this dad
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dad.
	 *
	 * @param description the description of this dad
	 */
	public void setDescription(String description);

}