/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ru.kashtanov.dad.model.impl;

import ru.kashtanov.dad.model.Dad;
import ru.kashtanov.dad.service.DadLocalServiceUtil;

/**
 * The extended model base implementation for the Dad service. Represents a row in the &quot;Dad_Dad&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DadImpl
 * @see Dad
 * @generated
 */
public abstract class DadBaseImpl extends DadModelImpl implements Dad {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dad model instance should use the <code>Dad</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DadLocalServiceUtil.addDad(this);
		}
		else {
			DadLocalServiceUtil.updateDad(this);
		}
	}

}